export const INSTALL_RATE_KEYS = [
  "install_pair_day_rate",
  "install_hotel_rate",
  "install_hotel_rate_abroad",
  "install_mileage_rate",
  "install_sensors_per_day",
  "install_displays_per_day",
  "install_eurotunnel",
  "install_contingency_low",
  "install_contingency_high",
  "install_out_of_hours_multiplier",
  "install_partial_infra_uplift",
  "install_no_infra_uplift",
  "install_flight_europe",
] as const;
